# Generated by Django 6.0.3 on 2026-04-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationcategory',
            options={'verbose_name_plural': 'Organization Categories'},
        ),
    ]
