# Generated by Django 6.0.3 on 2026-04-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_add_polls'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='scope',
            field=models.CharField(choices=[('system_wide', 'System Wide'), ('org_level', 'Org Level')], default='org_level', max_length=20),
        ),
        migrations.AlterField(
            model_name='poll',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='organizations.organization'),
        ),
    ]
