# Generated by Django 6.0.3 on 2026-04-19 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_name_orgalbum_orgphoto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgshowcase',
            name='album',
        ),
        migrations.AddField(
            model_name='orgshowcase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='org_showcase/'),
        ),
        migrations.AddField(
            model_name='orgvideopost',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='organizations.orgalbum'),
        ),
    ]
