# Generated by Django 6.0.3 on 2026-04-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_remove_orgshowcase_album_orgshowcase_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgvideopost',
            name='album',
        ),
    ]
