# Generated by Django 6.0.3 on 2026-04-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_remove_orgvideopost_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgphoto',
            options={'ordering': ['position', 'uploaded_at']},
        ),
        migrations.AddField(
            model_name='orgphoto',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='orgphoto',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
