# Generated by Django 6.0.3 on 2026-05-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_add_showcase_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgshowcase',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description shown on hover (max 50 chars)', max_length=50),
        ),
    ]
