# Generated by Django 6.0.3 on 2026-05-28 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_fix_cso_member_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditationapplication',
            name='registration_type',
            field=models.CharField(choices=[('new_applicant', 'New Applicant'), ('claim_existing', 'Claim Existing Organization'), ('new_chapter', 'New Chapter'), ('renewal', 'Renewal')], max_length=20),
        ),
        migrations.CreateModel(
            name='OrganizationRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100)),
                ('org_registration_number', models.CharField(blank=True, max_length=50)),
                ('proof_message', models.TextField(help_text="Brief explanation of org's official status in campus")),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='org_registration_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_org_registrations', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
