# Generated by Django 6.0.3 on 2026-05-28 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_alter_accreditationapplication_registration_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationregistration',
            name='proposed_chairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_chairman_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
