# Generated by Django 6.0.3 on 2026-05-28 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_organizationregistration_proposed_chairman'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('probationary', 'Probationary'), ('institutional', 'Institutional'), ('active', 'Active')], max_length=20, unique=True)),
                ('required_documents', models.JSONField(default=list, help_text='List of required document types for renewal')),
                ('optional_documents', models.JSONField(blank=True, default=list, help_text='List of optional document types for renewal')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_renewal_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Renewal Requirements',
            },
        ),
    ]
