# Generated by Django 6.0.3 on 2026-05-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_renewalrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationregistration',
            name='category',
            field=models.CharField(choices=[('normal', 'Normal Organization'), ('ub_chapter', 'UB Chapter'), ('institutional', 'Institutional')], default='normal', max_length=20),
        ),
    ]
