# Generated by Django 6.0.3 on 2026-05-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_organization_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='category',
            field=models.CharField(choices=[('student', 'Student Organization'), ('ub_chapter', 'UB Chapter'), ('institutional', 'Institutional')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationregistration',
            name='category',
            field=models.CharField(choices=[('student', 'Student Organization'), ('ub_chapter', 'UB Chapter'), ('institutional', 'Institutional')], default='normal', max_length=20),
        ),
    ]
