# Generated by Django 6.0.3 on 2026-05-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_alter_organization_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditationapplication',
            name='registration_type',
            field=models.CharField(choices=[('new_applicant', 'New Applicant'), ('new_chapter', 'New Chapter'), ('renewal', 'Renewal/Accreditation')], max_length=20),
        ),
    ]
