# Generated by Django 6.0.5 on 2026-06-04 01:57

import organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_organization_pre_renewal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditationdocument',
            name='compilation_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accreditationdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=organizations.models.accreditation_doc_upload_path),
        ),
    ]
