# Generated by Django 6.0.5 on 2026-06-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_cso_members_to_officers'),
        ('organizations', '0024_fix_lapsed_org_is_active'),
    ]

    operations = [
    ]
