# Generated by Django 6.0.5 on 2026-06-07 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0025_merge_20260607_2015'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('new_applicant', 'New Applicant'), ('new_chapter', 'New Chapter')], max_length=20, unique=True)),
                ('required_documents', models.JSONField(default=list, help_text='List of {title, link, optional} objects')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_accreditation_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Accreditation Requirements',
            },
        ),
    ]
