# Generated by Django 6.0.3 on 2026-04-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionposition',
            name='target_role',
            field=models.CharField(choices=[('member', 'Member'), ('officer', 'Officer'), ('co_chairman', 'Co-chairman'), ('chairman', 'Chairman')], default='officer', max_length=20),
        ),
    ]
