# Generated by Django 6.0.3 on 2026-04-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_add_position_target_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='voters_all_members',
            new_name='voters_org_members',
        ),
        migrations.AddField(
            model_name='election',
            name='voters_org_officers',
            field=models.BooleanField(default=False),
        ),
    ]
