# Generated by Django 6.0.3 on 2026-05-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_nullable_election_datetimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('results_released', 'Results Released')], db_index=True, default='draft', max_length=20),
        ),
    ]
