# Generated by Django 6.0.5 on 2026-06-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_alter_election_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionposition',
            name='target_role',
            field=models.CharField(choices=[('member', 'Member'), ('officer', 'Officer'), ('co_chairman', 'Vice Chairman'), ('chairman', 'Chairman')], default='officer', max_length=20),
        ),
    ]
