# Generated by Django 6.0.3 on 2026-05-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_is_active_alter_user_is_cso_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='abbreviation',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
