# Generated by Django 6.0.3 on 2026-04-11 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
        ('organizations', '0002_alter_organizationcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='pending_custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_memberships', to='organizations.role'),
        ),
        migrations.AddField(
            model_name='membership',
            name='pending_role',
            field=models.CharField(blank=True, choices=[('member', 'Member'), ('officer', 'Officer'), ('co_chairman', 'Co-chairman'), ('chairman', 'Chairman')], max_length=20, null=True),
        ),
    ]
