# Generated by Django 6.0.3 on 2026-05-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_add_pending_role_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('officer', 'Officer'), ('co_chairman', 'Co-chairman'), ('chairman', 'Chairman')], db_index=True, default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('left', 'Left'), ('removed', 'Removed')], db_index=True, default='active', max_length=20),
        ),
    ]
