# Generated by Django 6.0.5 on 2026-06-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_alter_membership_pending_role_alter_membership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='pending_role',
            field=models.CharField(blank=True, choices=[('member', 'Member'), ('officer', 'Officer'), ('co_chairman', 'Vice Chairman'), ('adviser', 'Adviser'), ('chairman', 'Chairman')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('officer', 'Officer'), ('co_chairman', 'Vice Chairman'), ('adviser', 'Adviser'), ('chairman', 'Chairman')], db_index=True, default='member', max_length=20),
        ),
    ]
