# Generated by Django 6.0.5 on 2026-06-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_add_adviser_role_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='adviser_since',
            field=models.DateTimeField(blank=True, help_text='Set when promoted to adviser; cleared on demotion or school year transition. Used to prevent chairman from bypassing adviser vote exclusion by demoting before election opens.', null=True),
        ),
    ]
