# Generated by Django 6.0.3 on 2026-05-27 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_set_org_status_from_is_active'),
        ('reports', '0002_alter_accomplishmentreport_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishmentreport',
            name='academic_year',
            field=models.CharField(blank=True, default='', help_text='e.g. 2024–2025', max_length=20),
        ),
        migrations.AddField(
            model_name='accomplishmentreport',
            name='activity_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='accomplishmentreport',
            name='date_of_activity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accomplishmentreport',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('Summer', 'Summer')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='ReportCompilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compilations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_compilations', to='organizations.organization')),
                ('reports', models.ManyToManyField(blank=True, related_name='compilations', to='reports.accomplishmentreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
