# Generated by Django 6.0.3 on 2026-05-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_backfill_notification_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='announcementreaction',
            name='reaction',
            field=models.CharField(choices=[('heart', 'Heart')], default='seen', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('membership', 'Membership'), ('election', 'Election'), ('report', 'Report'), ('organization', 'Organization'), ('system', 'System'), ('profile', 'Profile'), ('noteboard', 'Noteboard')], max_length=50, null=True),
        ),
    ]
