# Generated by Django 6.0.3 on 2026-04-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlet', '0002_alter_post_options_post_position_post_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_pinned', 'position', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='column',
        ),
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='emoji',
            field=models.CharField(choices=[('approve', '👍'), ('disapprove', '👎')], max_length=10),
        ),
    ]
