# Generated by Django 6.0.3 on 2026-05-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlet', '0010_remove_canvas_fields_update_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='attachment_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('url', 'URL Link')], max_length=10),
        ),
    ]
