# Generated by Django 6.0.3 on 2026-05-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlet', '0012_board_allow_multiple_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreaction',
            name='emoji',
            field=models.CharField(choices=[('thumbsup', '👍'), ('thumbsdown', '👎')], max_length=15),
        ),
    ]
