# Generated by Django 6.0.3 on 2026-05-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlet', '0013_alter_postreaction_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Make this org board visible to all students (only applies to org boards)'),
        ),
    ]
