# Generated by Django 6.0.3 on 2026-05-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padlet', '0014_board_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='is_public',
        ),
    ]
